import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { AppScreen, InlineState, ScreenHeader, SectionTitle, StatusBadge, uiStyles } from "@/components/operational-ui";
import { Colors } from "@/constants/Colors";
import { operationalService } from "@/services/operational.service";
import type { StudentAssignment, StudentDepartureDetail } from "@/types/operational";
import { getOperationalErrorMessage } from "@/utils/error-message";
import { formatGuayaquilDate, formatGuayaquilDateTime, formatOperationalTime, getDirectionLabel } from "@/utils/operational";

export default function DepartureDetailScreen() {
  const { departureId } = useLocalSearchParams<{ departureId: string }>(); const router = useRouter(); const [departure, setDeparture] = useState<StudentDepartureDetail | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!departureId) return; try { setLoading(true); setError(null); setDeparture(await operationalService.getStudentDeparture(departureId)); } catch (requestError) { setError(getOperationalErrorMessage(requestError)); } finally { setLoading(false); } }, [departureId]); useEffect(() => { const initialLoad = setTimeout(() => { void load(); }, 0); return () => clearTimeout(initialLoad); }, [load]);
  if (loading) return <AppScreen><ScreenHeader title="Detalle de salida" back onBack={() => router.back()} /><View style={styles.loading}><ActivityIndicator color={Colors.primary} size="large" /></View></AppScreen>;
  if (error || !departure) return <AppScreen><ScreenHeader title="Detalle de salida" back onBack={() => router.back()} /><InlineState icon="cloud-offline-outline" title="No pudimos cargar la salida" message={error || "La salida no está disponible."} action={<Pressable onPress={() => void load()}><Text style={styles.retry}>Reintentar</Text></Pressable>} /></AppScreen>;
  return <AppScreen><ScreenHeader title="Detalle de salida" subtitle={departure.serviceLine.name} back onBack={() => router.back()} /><ScrollView contentContainerStyle={uiStyles.scrollContent}><View style={styles.summary}><View><Text style={styles.time}>{formatOperationalTime(departure.scheduledTime)}</Text><Text style={styles.date}>{formatGuayaquilDate(departure.serviceDate)} · {getDirectionLabel(departure.direction)}</Text></View><StatusBadge state={departure.state} /></View><View style={styles.context}><Ionicons name="business-outline" size={18} color={Colors.primary} /><Text style={styles.contextText}>{departure.serviceLine.campus.name} · {departure.serviceLine.code}</Text></View><SectionTitle>Asignaciones por bus</SectionTitle>{departure.assignments.length === 0 ? <InlineState icon="bus-outline" title="Aún no hay buses asignados" message="La salida está programada, pero la operación todavía no ha asignado un bus." /> : departure.assignments.map((assignment) => <StudentAssignmentCard assignment={assignment} key={assignment.id} />)}</ScrollView></AppScreen>;
}

function StudentAssignmentCard({ assignment }: { assignment: StudentAssignment }) { return <View style={styles.assignment}><View style={styles.assignmentTop}><View style={styles.vehicleIcon}><Ionicons name="bus-outline" size={24} color={Colors.primary} /></View><View style={styles.assignmentCopy}><Text style={styles.vehicle}>{assignment.vehicle.code}</Text><Text style={styles.plate}>{assignment.vehicle.plate} · {assignment.vehicle.capacity} cupos</Text></View><StatusBadge state={assignment.operationStatus} /></View><View style={styles.meta}><Ionicons name="person-outline" size={17} color={Colors.text.light} /><Text style={styles.metaText}>{assignment.driverName || "Conductor por confirmar"}</Text></View><View style={styles.meta}><Ionicons name="time-outline" size={17} color={Colors.text.light} /><Text style={styles.metaText}>{formatGuayaquilDateTime(assignment.plannedStartAt)} — {formatGuayaquilDateTime(assignment.plannedEndAt)}</Text></View><View style={styles.route}><Text style={styles.routeTitle}>{assignment.journey.displayName}</Text>{assignment.journey.stops.map((stop) => <View key={stop.id} style={styles.stop}><View style={styles.stopMarker}><Text style={styles.stopOrder}>{stop.order}</Text></View><View style={styles.stopCopy}><Text style={styles.stopName}>{stop.name}</Text>{stop.reference ? <Text style={styles.stopReference}>{stop.reference}</Text> : null}</View></View>)}</View></View>; }
const styles = StyleSheet.create({ loading: { flex: 1, alignItems: "center", justifyContent: "center" }, retry: { color: Colors.primary, fontFamily: "Inter-SemiBold", fontSize: 15, marginTop: 12 }, summary: { padding: 20, borderRadius: 18, backgroundColor: Colors.navy, flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, time: { color: Colors.white, fontFamily: "Inter-Bold", fontSize: 32 }, date: { color: "#D6E4F3", fontFamily: "Inter-Regular", fontSize: 14, marginTop: 5 }, context: { flexDirection: "row", gap: 9, alignItems: "center", padding: 14, borderRadius: 14, backgroundColor: Colors.background.alt }, contextText: { flex: 1, color: Colors.primary, fontFamily: "Inter-SemiBold", fontSize: 13 }, assignment: { backgroundColor: Colors.white, borderRadius: 16, padding: 16, gap: 13, shadowColor: Colors.navy, shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 1 }, assignmentTop: { flexDirection: "row", alignItems: "center", gap: 10 }, vehicleIcon: { width: 44, height: 44, borderRadius: 13, backgroundColor: Colors.background.alt, alignItems: "center", justifyContent: "center" }, assignmentCopy: { flex: 1, gap: 3 }, vehicle: { color: Colors.text.dark, fontFamily: "Inter-SemiBold", fontSize: 16 }, plate: { color: Colors.text.light, fontFamily: "Inter-Regular", fontSize: 12 }, meta: { flexDirection: "row", gap: 8, alignItems: "flex-start" }, metaText: { flex: 1, color: Colors.text.light, fontFamily: "Inter-Regular", fontSize: 13, lineHeight: 19 }, route: { paddingTop: 12, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: Colors.border, gap: 10 }, routeTitle: { color: Colors.text.dark, fontFamily: "Inter-SemiBold", fontSize: 14 }, stop: { flexDirection: "row", gap: 10, alignItems: "flex-start" }, stopMarker: { width: 24, height: 24, borderRadius: 12, backgroundColor: Colors.background.alt, justifyContent: "center", alignItems: "center" }, stopOrder: { color: Colors.primary, fontFamily: "Inter-Bold", fontSize: 11 }, stopCopy: { flex: 1 }, stopName: { color: Colors.text.dark, fontFamily: "Inter-Regular", fontSize: 13 }, stopReference: { color: Colors.text.light, fontFamily: "Inter-Regular", fontSize: 12, marginTop: 2 }, });
