import { useCallback, useEffect, useState } from "react";
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { AppScreen, InlineState, ListSkeleton, ScreenHeader, StatusBadge, uiStyles } from "@/components/operational-ui";
import { Colors } from "@/constants/Colors";
import { operationalService } from "@/services/operational.service";
import type { DepartureSummary, Direction } from "@/types/operational";
import { getOperationalErrorMessage } from "@/utils/error-message";
import { formatGuayaquilDate, formatOperationalTime, getDirectionLabel, getGuayaquilToday, shiftCivilDate } from "@/utils/operational";

export default function DeparturesScreen() {
  const { serviceLineId, name } = useLocalSearchParams<{ serviceLineId: string; name?: string }>(); const router = useRouter(); const [direction, setDirection] = useState<Direction>("IDA"); const [date, setDate] = useState(getGuayaquilToday); const [departures, setDepartures] = useState<DepartureSummary[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async (refresh = false) => { if (!serviceLineId) return; try { if (refresh) setRefreshing(true); else setLoading(true); setError(null); setDepartures(await operationalService.getDepartures(serviceLineId, date, direction)); } catch (requestError) { setError(getOperationalErrorMessage(requestError)); } finally { setLoading(false); setRefreshing(false); } }, [date, direction, serviceLineId]); useEffect(() => { const initialLoad = setTimeout(() => { void load(); }, 0); return () => clearTimeout(initialLoad); }, [load]);
  return <AppScreen><ScreenHeader title={name || "Salidas"} subtitle="Horarios por fecha y sentido" back onBack={() => router.back()} /><View style={styles.controls}><View style={styles.dateRow}><Pressable accessibilityRole="button" accessibilityLabel="Día anterior" onPress={() => setDate((value) => shiftCivilDate(value, -1))} style={styles.dateButton}><Ionicons name="chevron-back" size={20} color={Colors.primary} /></Pressable><View style={styles.dateCopy}><Text style={styles.dateLabel}>{date === getGuayaquilToday() ? "Hoy" : "Fecha seleccionada"}</Text><Text style={styles.dateValue}>{formatGuayaquilDate(date)}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Día siguiente" onPress={() => setDate((value) => shiftCivilDate(value, 1))} style={styles.dateButton}><Ionicons name="chevron-forward" size={20} color={Colors.primary} /></Pressable></View><View style={styles.directionRow}>{(["IDA", "RETORNO"] as const).map((option) => <Pressable key={option} accessibilityRole="button" accessibilityState={{ selected: direction === option }} style={[styles.direction, direction === option && styles.directionActive]} onPress={() => setDirection(option)}><Text style={[styles.directionText, direction === option && styles.directionTextActive]}>{getDirectionLabel(option)}</Text></Pressable>)}</View></View>{loading ? <ListSkeleton /> : error ? <InlineState icon="cloud-offline-outline" title="No pudimos consultar las salidas" message={error} action={<Pressable onPress={() => void load()}><Text style={styles.retry}>Reintentar</Text></Pressable>} /> : <FlatList data={departures} keyExtractor={(item) => item.id} contentContainerStyle={uiStyles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={Colors.primary} />} ListEmptyComponent={<InlineState icon="calendar-clear-outline" title="Sin salidas programadas" message={`No hay salidas de ${getDirectionLabel(direction).toLowerCase()} para esta fecha.`} />} renderItem={({ item }) => <Pressable accessibilityRole="button" style={({ pressed }) => [styles.card, pressed && uiStyles.cardPressed]} onPress={() => router.push({ pathname: "/(student)/scheduled-departure/[departureId]", params: { departureId: item.id } })}><View style={styles.time}><Text style={styles.timeValue}>{formatOperationalTime(item.scheduledTime)}</Text><Text style={styles.directionHint}>{getDirectionLabel(item.direction)}</Text></View><View style={styles.cardCopy}><StatusBadge state={item.state} /><Text style={styles.assignmentText}>{item.assignmentCount === 0 ? "Aún sin buses asignados" : item.assignmentCount === 1 ? "1 bus asignado" : `${item.assignmentCount} buses asignados`}</Text></View><Ionicons name="chevron-forward" size={20} color={Colors.text.light} /></Pressable>} />}</AppScreen>;
}

const styles = StyleSheet.create({ controls: { padding: 20, paddingBottom: 4, gap: 12 }, dateRow: { minHeight: 56, borderRadius: 16, backgroundColor: Colors.white, flexDirection: "row", alignItems: "center", paddingHorizontal: 6, shadowColor: Colors.navy, shadowOpacity: 0.05, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 1 }, dateButton: { width: 44, height: 44, alignItems: "center", justifyContent: "center" }, dateCopy: { flex: 1, alignItems: "center" }, dateLabel: { color: Colors.text.light, fontFamily: "Inter-Regular", fontSize: 12 }, dateValue: { color: Colors.text.dark, fontFamily: "Inter-SemiBold", fontSize: 15, marginTop: 2 }, directionRow: { backgroundColor: Colors.background.alt, borderRadius: 14, padding: 4, flexDirection: "row" }, direction: { flex: 1, minHeight: 40, borderRadius: 10, alignItems: "center", justifyContent: "center" }, directionActive: { backgroundColor: Colors.white, shadowColor: Colors.navy, shadowOpacity: 0.08, shadowRadius: 6, shadowOffset: { width: 0, height: 2 }, elevation: 1 }, directionText: { color: Colors.text.light, fontFamily: "Inter-SemiBold", fontSize: 14 }, directionTextActive: { color: Colors.primary }, card: { backgroundColor: Colors.white, borderRadius: 16, padding: 16, flexDirection: "row", alignItems: "center", gap: 14, shadowColor: Colors.navy, shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 1 }, time: { width: 62, alignItems: "center", paddingRight: 12, borderRightWidth: StyleSheet.hairlineWidth, borderRightColor: Colors.border }, timeValue: { color: Colors.navy, fontFamily: "Inter-Bold", fontSize: 19 }, directionHint: { color: Colors.text.light, fontFamily: "Inter-Regular", fontSize: 11, marginTop: 2 }, cardCopy: { flex: 1, gap: 9 }, assignmentText: { color: Colors.text.light, fontFamily: "Inter-Regular", fontSize: 13 }, retry: { color: Colors.primary, fontFamily: "Inter-SemiBold", fontSize: 15, marginTop: 12 }, });
