import { Pressable, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { Colors } from "@/constants/Colors";
import { StatusBadge, uiStyles } from "@/components/operational-ui";
import type { DriverAssignment } from "@/types/operational";
import { formatGuayaquilDateTime, formatOperationalTime, getDirectionLabel } from "@/utils/operational";

export function DriverAssignmentCard({ assignment, onPress }: { assignment: DriverAssignment; onPress: () => void }) {
  return <Pressable accessibilityRole="button" style={({ pressed }) => [styles.card, pressed && uiStyles.cardPressed]} onPress={onPress}><View style={styles.top}><View><Text style={styles.time}>{formatOperationalTime(assignment.departure.scheduledTime)}</Text><Text style={styles.line}>{assignment.departure.serviceLine.name} · {getDirectionLabel(assignment.departure.direction)}</Text></View><StatusBadge state={assignment.operationalStatus} /></View><View style={styles.detail}><Ionicons name="bus-outline" size={17} color={Colors.primary} /><Text style={styles.detailText}>{assignment.vehicle.code} · {assignment.vehicle.plate}</Text></View><View style={styles.detail}><Ionicons name="time-outline" size={17} color={Colors.primary} /><Text style={styles.detailText}>{formatGuayaquilDateTime(assignment.plannedStartAt)} — {formatGuayaquilDateTime(assignment.plannedEndAt)}</Text></View><View style={styles.footer}><Text style={styles.path}>{assignment.journey.routePath.displayName}</Text><Ionicons name="chevron-forward" size={20} color={Colors.text.light} /></View></Pressable>;
}
const styles = StyleSheet.create({ card: { backgroundColor: Colors.white, borderRadius: 16, padding: 16, gap: 11, shadowColor: Colors.navy, shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 1 }, top: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 10 }, time: { color: Colors.navy, fontFamily: "Inter-Bold", fontSize: 22 }, line: { color: Colors.text.dark, fontFamily: "Inter-SemiBold", fontSize: 14, marginTop: 2, maxWidth: 210 }, detail: { flexDirection: "row", alignItems: "flex-start", gap: 8 }, detailText: { flex: 1, color: Colors.text.light, fontFamily: "Inter-Regular", fontSize: 13, lineHeight: 18 }, footer: { flexDirection: "row", alignItems: "center", gap: 8, paddingTop: 11, borderTopColor: Colors.border, borderTopWidth: StyleSheet.hairlineWidth }, path: { flex: 1, color: Colors.primary, fontFamily: "Inter-SemiBold", fontSize: 13 }, });
