import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { AppScreen, ScreenHeader, uiStyles } from "@/components/operational-ui";
import { Colors } from "@/constants/Colors";
import { useAuth } from "@/context/AuthContext";
import { getDisplayName } from "@/utils/operational";

export function ProfileScreen({ roleLabel }: { roleLabel: string }) {
  const { user, logout } = useAuth();
  const displayName = getDisplayName(user?.name, user?.email);
  const initials = displayName.split(" ").filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "UG";
  const requestLogout = () => Alert.alert("Cerrar sesión", "Tendrás que volver a verificar tu correo para ingresar.", [{ text: "Cancelar", style: "cancel" }, { text: "Cerrar sesión", style: "destructive", onPress: () => { void logout(); } }]);
  return <AppScreen><ScreenHeader title="Perfil" subtitle={roleLabel} /><ScrollView contentContainerStyle={uiStyles.scrollContent}><View style={styles.profile}><View style={styles.avatar}><Text style={styles.initials}>{initials}</Text></View><Text style={styles.name}>{displayName}</Text><Text style={styles.email}>{user?.email ?? ""}</Text><View style={styles.role}><Ionicons name="shield-checkmark-outline" size={15} color={Colors.primary} /><Text style={styles.roleText}>{roleLabel}</Text></View></View><View style={uiStyles.card}><View style={styles.infoRow}><Ionicons name="information-circle-outline" size={21} color={Colors.primary} /><View style={styles.infoCopy}><Text style={styles.infoTitle}>Acerca de UPS GO</Text><Text style={styles.infoText}>La información del servicio se actualiza desde la operación universitaria.</Text></View></View></View><Pressable accessibilityRole="button" style={({ pressed }) => [styles.logout, pressed && uiStyles.cardPressed]} onPress={requestLogout}><Ionicons name="log-out-outline" size={20} color={Colors.error} /><Text style={styles.logoutText}>Cerrar sesión</Text></Pressable><Text style={styles.version}>UPS GO · versión 1.0.1</Text></ScrollView></AppScreen>;
}

const styles = StyleSheet.create({ profile: { backgroundColor: Colors.white, borderRadius: 18, padding: 24, alignItems: "center", gap: 7, shadowColor: Colors.navy, shadowOpacity: 0.07, shadowRadius: 14, shadowOffset: { width: 0, height: 6 }, elevation: 2 }, avatar: { width: 76, height: 76, borderRadius: 38, backgroundColor: Colors.navy, alignItems: "center", justifyContent: "center", marginBottom: 6 }, initials: { color: Colors.white, fontFamily: "Inter-Bold", fontSize: 25 }, name: { color: Colors.text.dark, fontFamily: "Inter-Bold", fontSize: 20, textAlign: "center" }, email: { color: Colors.text.light, fontFamily: "Inter-Regular", fontSize: 14, textAlign: "center" }, role: { flexDirection: "row", gap: 6, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: Colors.background.alt, marginTop: 5, alignItems: "center" }, roleText: { color: Colors.primary, fontFamily: "Inter-SemiBold", fontSize: 12 }, infoRow: { flexDirection: "row", gap: 12, alignItems: "flex-start" }, infoCopy: { flex: 1, gap: 4 }, infoTitle: { color: Colors.text.dark, fontFamily: "Inter-SemiBold", fontSize: 15 }, infoText: { color: Colors.text.light, fontFamily: "Inter-Regular", fontSize: 13, lineHeight: 19 }, logout: { minHeight: 52, borderRadius: 14, backgroundColor: "#FDE9E7", alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8 }, logoutText: { color: Colors.error, fontFamily: "Inter-SemiBold", fontSize: 15 }, version: { color: Colors.text.light, fontFamily: "Inter-Regular", fontSize: 12, textAlign: "center", marginTop: 8 }, });
