import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { AppScreen, InlineState, PrimaryButton, ScreenHeader, SectionTitle, uiStyles } from "@/components/operational-ui";
import { DriverAssignmentCard } from "@/components/driver-assignment-card";
import { Colors } from "@/constants/Colors";
import { useAuth } from "@/context/AuthContext";
import { operationalService } from "@/services/operational.service";
import type { DriverAssignment } from "@/types/operational";
import { getOperationalErrorMessage } from "@/utils/error-message";
import { getDisplayName } from "@/utils/operational";

export default function DriverHomeScreen() {
  const router = useRouter(); const { user } = useAuth(); const [current, setCurrent] = useState<DriverAssignment | null>(null); const [assignments, setAssignments] = useState<DriverAssignment[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null); const name = getDisplayName(user?.name, user?.email).split(" ")[0];
  const load = useCallback(async (refresh = false) => { try { if (refresh) setRefreshing(true); else setLoading(true); setError(null); const [currentRun, todayAssignments] = await Promise.all([operationalService.getCurrentDriverRun(), operationalService.getDriverAssignmentsToday()]); setCurrent(currentRun); setAssignments(todayAssignments); } catch (requestError) { setError(getOperationalErrorMessage(requestError)); } finally { setLoading(false); setRefreshing(false); } }, []); useEffect(() => { const initialLoad = setTimeout(() => { void load(); }, 0); return () => clearTimeout(initialLoad); }, [load]);
  return <AppScreen><ScreenHeader title="UPS GO" subtitle="Operación de conductor" />{loading ? <View style={styles.loading}><ActivityIndicator color={Colors.primary} size="large" /></View> : error ? <InlineState icon="cloud-offline-outline" title="No pudimos cargar tu jornada" message={error} action={<PrimaryButton label="Reintentar" onPress={() => void load()} tone="outline" />} /> : <ScrollView contentContainerStyle={uiStyles.scrollContent} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={Colors.primary} />}><View style={styles.hero}><Text style={styles.greeting}>Hola, {name}</Text><Text style={styles.heroText}>{current ? "Tienes un recorrido en curso." : assignments.length ? "Revisa tus asignaciones de hoy." : "No tienes servicios asignados para hoy."}</Text>{current?.run ? <PrimaryButton label="Continuar recorrido" icon="navigate" tone="gold" onPress={() => router.push({ pathname: "/(driver)/run/[runId]", params: { runId: current.run!.id } })} /> : <Pressable style={({ pressed }) => [styles.heroLink, pressed && uiStyles.cardPressed]} onPress={() => router.push("/(driver)/(tabs)/assignments")}><Text style={styles.heroLinkText}>Ver mis servicios</Text><Ionicons name="arrow-forward" size={19} color={Colors.white} /></Pressable>}</View>{current ? <><SectionTitle>Recorrido actual</SectionTitle><DriverAssignmentCard assignment={current} onPress={() => current.run && router.push({ pathname: "/(driver)/run/[runId]", params: { runId: current.run.id } })} /></> : null}<SectionTitle>Próximos servicios</SectionTitle>{assignments.filter((assignment) => assignment.id !== current?.id).length === 0 ? <InlineState icon="calendar-clear-outline" title="Sin servicios pendientes" message="Cuando la operación te asigne un servicio, aparecerá aquí." /> : assignments.filter((assignment) => assignment.id !== current?.id).slice(0, 2).map((assignment) => <DriverAssignmentCard key={assignment.id} assignment={assignment} onPress={() => router.push({ pathname: "/(driver)/assignment/[assignmentId]", params: { assignmentId: assignment.id } })} />)}<Pressable accessibilityRole="button" onPress={() => router.push("/(driver)/(tabs)/assignments")} style={styles.allLink}><Text style={styles.allLinkText}>Ver todos mis servicios</Text><Ionicons name="chevron-forward" size={18} color={Colors.primary} /></Pressable></ScrollView>}</AppScreen>;
}
const styles = StyleSheet.create({ loading: { flex: 1, alignItems: "center", justifyContent: "center" }, hero: { backgroundColor: Colors.navy, borderRadius: 20, padding: 20, gap: 11 }, greeting: { color: Colors.white, fontFamily: "Inter-Bold", fontSize: 25 }, heroText: { color: "#D6E4F3", fontFamily: "Inter-Regular", fontSize: 15, lineHeight: 22 }, heroLink: { minHeight: 46, marginTop: 6, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8, borderRadius: 14, backgroundColor: Colors.primary }, heroLinkText: { color: Colors.white, fontFamily: "Inter-SemiBold", fontSize: 15 }, allLink: { minHeight: 44, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 4 }, allLinkText: { color: Colors.primary, fontFamily: "Inter-SemiBold", fontSize: 14 }, });
