import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { AppScreen, InlineState, PrimaryButton, ScreenHeader, SectionTitle, StatusBadge, uiStyles } from "@/components/operational-ui";
import { Colors } from "@/constants/Colors";
import { operationalService } from "@/services/operational.service";
import type { DriverAssignment } from "@/types/operational";
import { getOperationalErrorMessage } from "@/utils/error-message";
import { formatGuayaquilDateTime, formatOperationalTime, getDirectionLabel } from "@/utils/operational";

export default function AssignmentDetailScreen() {
  const { assignmentId } = useLocalSearchParams<{ assignmentId: string }>(); const router = useRouter(); const [assignment, setAssignment] = useState<DriverAssignment | null>(null); const [loading, setLoading] = useState(true); const [starting, setStarting] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!assignmentId) return; try { setLoading(true); setError(null); setAssignment(await operationalService.getDriverAssignment(assignmentId)); } catch (requestError) { setError(getOperationalErrorMessage(requestError)); } finally { setLoading(false); } }, [assignmentId]); useEffect(() => { const initialLoad = setTimeout(() => { void load(); }, 0); return () => clearTimeout(initialLoad); }, [load]);
  const start = () => Alert.alert("Iniciar recorrido", "Confirmas que inicias este servicio asignado?", [{ text: "Cancelar", style: "cancel" }, { text: "Iniciar", onPress: () => { void startConfirmed(); } }]);
  const startConfirmed = async () => { if (!assignment) return; try { setStarting(true); setError(null); const updated = await operationalService.startDriverRun(assignment.id); setAssignment(updated); if (updated.run) router.replace({ pathname: "/(driver)/run/[runId]", params: { runId: updated.run.id } }); } catch (requestError) { setError(getOperationalErrorMessage(requestError)); } finally { setStarting(false); } };
  if (loading) return <AppScreen><ScreenHeader title="Detalle del servicio" back onBack={() => router.back()} /><View style={styles.loading}><ActivityIndicator size="large" color={Colors.primary} /></View></AppScreen>;
  if (error || !assignment) return <AppScreen><ScreenHeader title="Detalle del servicio" back onBack={() => router.back()} /><InlineState icon="cloud-offline-outline" title="No pudimos cargar el servicio" message={error || "El servicio no está disponible."} action={<Pressable onPress={() => void load()}><Text style={styles.retry}>Reintentar</Text></Pressable>} /></AppScreen>;
  return <AppScreen><ScreenHeader title="Detalle del servicio" subtitle={assignment.departure.serviceLine.name} back onBack={() => router.back()} /><ScrollView contentContainerStyle={uiStyles.scrollContent}><View style={styles.summary}><View><Text style={styles.time}>{formatOperationalTime(assignment.departure.scheduledTime)}</Text><Text style={styles.line}>{getDirectionLabel(assignment.departure.direction)} · {assignment.departure.serviceLine.campus.name}</Text></View><StatusBadge state={assignment.operationalStatus} /></View><View style={styles.info}><InfoRow icon="bus-outline" label="Vehículo" value={`${assignment.vehicle.code} · ${assignment.vehicle.plate}`} /><InfoRow icon="time-outline" label="Ventana planificada" value={`${formatGuayaquilDateTime(assignment.plannedStartAt)} — ${formatGuayaquilDateTime(assignment.plannedEndAt)}`} /></View><SectionTitle>Recorrido asignado</SectionTitle><View style={styles.route}><Text style={styles.routeName}>{assignment.journey.routePath.displayName}</Text>{assignment.journey.routePath.stops.map((stop) => <View key={stop.stop.id} style={styles.stop}><View style={styles.marker}><Text style={styles.markerText}>{stop.stopOrder}</Text></View><View style={styles.stopCopy}><Text style={styles.stopName}>{stop.stop.name}</Text>{stop.stop.reference ? <Text style={styles.stopReference}>{stop.stop.reference}</Text> : null}</View></View>)}</View>{error ? <Text style={styles.inlineError}>{error}</Text> : null}{assignment.run?.id ? <PrimaryButton label="Ver recorrido actual" icon="navigate" tone="gold" onPress={() => router.push({ pathname: "/(driver)/run/[runId]", params: { runId: assignment.run!.id } })} /> : <PrimaryButton label="Iniciar recorrido" icon="play" loading={starting} disabled={assignment.operationalStatus !== "ASSIGNED"} onPress={start} />}</ScrollView></AppScreen>;
}
function InfoRow({ icon, label, value }: { icon: keyof typeof Ionicons.glyphMap; label: string; value: string }) { return <View style={styles.infoRow}><Ionicons name={icon} size={20} color={Colors.primary} /><View style={styles.infoCopy}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View></View>; }
const styles = StyleSheet.create({ loading: { flex: 1, justifyContent: "center", alignItems: "center" }, retry: { color: Colors.primary, fontFamily: "Inter-SemiBold", fontSize: 15, marginTop: 12 }, summary: { backgroundColor: Colors.navy, padding: 20, borderRadius: 18, flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 12 }, time: { color: Colors.white, fontFamily: "Inter-Bold", fontSize: 32 }, line: { color: "#D6E4F3", fontFamily: "Inter-Regular", fontSize: 14, marginTop: 5 }, info: { backgroundColor: Colors.white, borderRadius: 16, padding: 16, gap: 16, shadowColor: Colors.navy, shadowOpacity: 0.05, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 1 }, infoRow: { flexDirection: "row", gap: 12, alignItems: "flex-start" }, infoCopy: { flex: 1, gap: 3 }, infoLabel: { color: Colors.text.light, fontFamily: "Inter-Regular", fontSize: 12 }, infoValue: { color: Colors.text.dark, fontFamily: "Inter-SemiBold", fontSize: 14, lineHeight: 20 }, route: { backgroundColor: Colors.white, borderRadius: 16, padding: 16, gap: 12, shadowColor: Colors.navy, shadowOpacity: 0.05, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 1 }, routeName: { color: Colors.text.dark, fontFamily: "Inter-SemiBold", fontSize: 16, marginBottom: 2 }, stop: { flexDirection: "row", gap: 10, alignItems: "flex-start" }, marker: { width: 25, height: 25, borderRadius: 13, backgroundColor: Colors.background.alt, justifyContent: "center", alignItems: "center" }, markerText: { color: Colors.primary, fontFamily: "Inter-Bold", fontSize: 11 }, stopCopy: { flex: 1 }, stopName: { color: Colors.text.dark, fontFamily: "Inter-Regular", fontSize: 14 }, stopReference: { color: Colors.text.light, fontFamily: "Inter-Regular", fontSize: 12, marginTop: 2 }, inlineError: { color: Colors.error, fontFamily: "Inter-Regular", fontSize: 13, textAlign: "center" }, });
