import { useCallback, useEffect, useState } from "react";
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { AppScreen, InlineState, ListSkeleton, ScreenHeader, uiStyles } from "@/components/operational-ui";
import { Colors } from "@/constants/Colors";
import { operationalService } from "@/services/operational.service";
import type { ServiceLine } from "@/types/operational";
import { getOperationalErrorMessage } from "@/utils/error-message";

export default function ServiceLinesScreen() {
  const { campusId, name } = useLocalSearchParams<{ campusId: string; name?: string }>(); const router = useRouter(); const [lines, setLines] = useState<ServiceLine[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async (refresh = false) => { if (!campusId) return; try { if (refresh) setRefreshing(true); else setLoading(true); setError(null); setLines(await operationalService.getServiceLines(campusId)); } catch (requestError) { setError(getOperationalErrorMessage(requestError)); } finally { setLoading(false); setRefreshing(false); } }, [campusId]); useEffect(() => { const initialLoad = setTimeout(() => { void load(); }, 0); return () => clearTimeout(initialLoad); }, [load]);
  return <AppScreen><ScreenHeader title="Líneas disponibles" subtitle={name || "Campus"} back onBack={() => router.back()} />{loading ? <ListSkeleton /> : error ? <InlineState icon="cloud-offline-outline" title="No pudimos cargar las líneas" message={error} action={<Pressable onPress={() => void load()}><Text style={styles.retry}>Reintentar</Text></Pressable>} /> : <FlatList data={lines} keyExtractor={(item) => item.id} contentContainerStyle={uiStyles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={Colors.primary} />} ListEmptyComponent={<InlineState icon="bus-outline" title="No hay líneas para este campus" message="Aún no hay líneas activas disponibles." />} renderItem={({ item }) => <Pressable accessibilityRole="button" style={({ pressed }) => [styles.card, pressed && uiStyles.cardPressed]} onPress={() => router.push({ pathname: "/(student)/service-line/[serviceLineId]", params: { serviceLineId: item.id, name: item.name } })}><View style={styles.icon}><Ionicons name="git-branch-outline" size={23} color={Colors.primary} /></View><View style={styles.copy}><Text style={styles.code}>{item.code}</Text><Text style={styles.name}>{item.name}</Text>{item.description ? <Text style={styles.detail}>{item.description}</Text> : null}</View><Ionicons name="chevron-forward" size={20} color={Colors.text.light} /></Pressable>} />}</AppScreen>;
}
const styles = StyleSheet.create({ card: { backgroundColor: Colors.white, borderRadius: 16, padding: 16, flexDirection: "row", alignItems: "center", gap: 14, shadowColor: Colors.navy, shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 1 }, icon: { width: 48, height: 48, borderRadius: 14, backgroundColor: Colors.background.alt, alignItems: "center", justifyContent: "center" }, copy: { flex: 1, gap: 3 }, code: { color: Colors.primary, fontFamily: "Inter-SemiBold", fontSize: 12 }, name: { color: Colors.text.dark, fontFamily: "Inter-SemiBold", fontSize: 16 }, detail: { color: Colors.text.light, fontFamily: "Inter-Regular", fontSize: 13, lineHeight: 18 }, retry: { color: Colors.primary, fontFamily: "Inter-SemiBold", fontSize: 15, marginTop: 12 }, });
